config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctor_profiles
  resources :patient_profiles
  devise_for :users
  get 'home/index'

 root 'home#index'

end

app/models/doctor_profile.rb
class DoctorProfile < ActiveRecord::Base
  belongs_to :user

    def full_name
  		[first_name, last_name].compact.join(' ')
    end
  mount_uploader :photo, DoctorProfilePhotoUploader

  
end

app/controllers/doctor_profiles_controller.rb
class DoctorProfilesController < ApplicationController
  before_action :set_doctor_profile, only: [:show, :edit, :update, :destroy]

  # GET /doctor_profiles
  # GET /doctor_profiles.json
  def index
    @doctor_profiles = DoctorProfile.all
  end

  # GET /doctor_profiles/1
  # GET /doctor_profiles/1.json
  def show
  end

  # GET /doctor_profiles/new
  def new
    @doctor_profile = DoctorProfile.new
  end

  # GET /doctor_profiles/1/edit
  def edit
  end

  # POST /doctor_profiles
  # POST /doctor_profiles.json
  def create
    @doctor_profile = DoctorProfile.new(doctor_profile_params)
    @doctor_profile.user = current_user
    respond_to do |format|
      if @doctor_profile.save
        format.html { redirect_to @doctor_profile, notice: 'Doctor profile was successfully created.' }
        format.json { render :show, status: :created, location: @doctor_profile }
      else
        format.html { render :new }
        format.json { render json: @doctor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctor_profiles/1
  # PATCH/PUT /doctor_profiles/1.json
  def update
    respond_to do |format|
      if @doctor_profile.update(doctor_profile_params)
        format.html { redirect_to @doctor_profile, notice: 'Doctor profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor_profile }
      else
        format.html { render :edit }
        format.json { render json: @doctor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctor_profiles/1
  # DELETE /doctor_profiles/1.json
  def destroy
    @doctor_profile.destroy
    respond_to do |format|
      format.html { redirect_to doctor_profiles_url, notice: 'Doctor profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_profile
      @doctor_profile = DoctorProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_profile_params
      params.require(:doctor_profile).permit(:title, :first_name, :last_name, :photo, :bio, :post_nominals, :user_id)
    end
end

app/helpers/doctor_profiles_helper.rb
module DoctorProfilesHelper
end

app/views/doctor_profiles/_form.html.erb
<%= simple_form_for(@doctor_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :photo %>
    <%= f.input :bio %>
    <%= f.input :post_nominals %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doctor_profiles/edit.html.erb
<h1>Editing Doctor Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor_profile %> |
<%= link_to 'Back', doctor_profiles_path %>

app/views/doctor_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctor Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Photo</th>
      <th>Bio</th>
      <th>Post nominals</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctor_profiles.each do |doctor_profile| %>
      <tr>
        <td><%= doctor_profile.title %></td>
        <td><%= doctor_profile.first_name %></td>
        <td><%= doctor_profile.last_name %></td>
        <td><%= doctor_profile.photo %></td>
        <td><%= doctor_profile.bio %></td>
        <td><%= doctor_profile.post_nominals %></td>
        <td><%= doctor_profile.user %></td>
        <td><%= link_to 'Show', doctor_profile %></td>
        <td><%= link_to 'Edit', edit_doctor_profile_path(doctor_profile) %></td>
        <td><%= link_to 'Destroy', doctor_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor profile', new_doctor_profile_path %>

app/views/doctor_profiles/new.html.erb
<h1>New Doctor Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', doctor_profiles_path %>

app/views/doctor_profiles/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Title:</strong>
  <%= @doctor_profile.title %>
</p>

<p>
  <strong>First name:</strong>
  <%= @doctor_profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @doctor_profile.last_name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @doctor_profile.photo, class: 'img-responsive img-circle', width: '300px' %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @doctor_profile.bio %>
</p>

<p>
  <strong>Post nominals:</strong>
  <%= @doctor_profile.post_nominals %>
</p>

<p>
  <strong>User:</strong>
  <%= @doctor_profile.user %>
</p>

<%= link_to 'Edit', edit_doctor_profile_path(@doctor_profile) %> |
<%= link_to 'Back', doctor_profiles_path %>