config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctor_profiles
  resources :patient_profiles
  devise_for :users
  get 'home/index'

 root 'home#index'

end

app/models/patient_profile.rb
class PatientProfile < ActiveRecord::Base
  belongs_to :user

  def full_name
  	[first_name, last_name].compact.join(' ')
  end
end

app/controllers/patient_profiles_controller.rb
class PatientProfilesController < ApplicationController
  before_action :set_patient_profile, only: [:show, :edit, :update, :destroy]

  # GET /patient_profiles
  # GET /patient_profiles.json
  def index
    @patient_profiles = PatientProfile.all
  end

  # GET /patient_profiles/1
  # GET /patient_profiles/1.json
  def show
  end

  # GET /patient_profiles/new
  def new
    @patient_profile = PatientProfile.new

  end

  # GET /patient_profiles/1/edit
  def edit
  end

  # POST /patient_profiles
  # POST /patient_profiles.json
  def create
    @patient_profile = PatientProfile.new(patient_profile_params)
    @patient_profile.user = current_user
    respond_to do |format|
      if @patient_profile.save
        format.html { redirect_to @patient_profile, notice: 'Patient profile was successfully created.' }
        format.json { render :show, status: :created, location: @patient_profile }
      else
        format.html { render :new }
        format.json { render json: @patient_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_profiles/1
  # PATCH/PUT /patient_profiles/1.json
  def update
    respond_to do |format|
      if @patient_profile.update(patient_profile_params)
        format.html { redirect_to @patient_profile, notice: 'Patient profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient_profile }
      else
        format.html { render :edit }
        format.json { render json: @patient_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_profiles/1
  # DELETE /patient_profiles/1.json
  def destroy
    @patient_profile.destroy
    respond_to do |format|
      format.html { redirect_to patient_profiles_url, notice: 'Patient profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_profile
      @patient_profile = PatientProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_profile_params
      params.require(:patient_profile).permit(:first_name, :last_name, :phone, :address, :suburb, :state, :postcode, :country, :latitude, :longitude, :medicare_number, :user_id)
    end
end

app/helpers/patient_profiles_helper.rb
module PatientProfilesHelper
end

app/views/patient_profiles/_form.html.erb
<%= simple_form_for(@patient_profile) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class = "col-md-6">
        <%= f.input :first_name %>
    </div>
    <div class = "col-md-6">
        <%= f.input :last_name %>
    </div>
  </div>
    <%= f.input :phone %>
    <%= f.input :address %>
    <%= f.input :suburb %>
    <%= f.input :state %>
    <%= f.input :postcode %>
    <%= f.input :country, priority: ['Australia',  'New Zealand'] %>
    <%= f.input :medicare_number %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/patient_profiles/edit.html.erb
<h1>Editing Patient Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient_profile %> |
<%= link_to 'Back', patient_profiles_path %>

app/views/patient_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patient Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Medicare number</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient_profiles.each do |patient_profile| %>
      <tr>
        <td><%= patient_profile.first_name %></td>
        <td><%= patient_profile.last_name %></td>
        <td><%= patient_profile.phone %></td>
        <td><%= patient_profile.address %></td>
        <td><%= patient_profile.suburb %></td>
        <td><%= patient_profile.state %></td>
        <td><%= patient_profile.postcode %></td>
        <td><%= patient_profile.country %></td>
        <td><%= patient_profile.latitude %></td>
        <td><%= patient_profile.longitude %></td>
        <td><%= patient_profile.medicare_number %></td>
        <td><%= patient_profile.user %></td>
        <td><%= link_to 'Show', patient_profile %></td>
        <td><%= link_to 'Edit', edit_patient_profile_path(patient_profile) %></td>
        <td><%= link_to 'Destroy', patient_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient profile', new_patient_profile_path %>

app/views/patient_profiles/new.html.erb
<div class = "row" >
<div class = "col-md-8 col-md-offset-2">

<h1>New Patient Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_profiles_path %>

</div>
</div>

app/views/patient_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <div class = "panel panel-default">
      <div class = "panel-body">
        <h2><%= @patient_profile.full_name %></h2>

        
<p>
  <strong>Phone:</strong>
  <%= @patient_profile.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient_profile.address %>
</p>

<br>

  <%= @patient_profile.suburb %>, <%= @patient_profile.state %>
  <%= @patient_profile.postcode %> <%= @patient_profile.country %>
</p>

<p>
  <strong>Medicare number:</strong>
  <%= @patient_profile.medicare_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient_profile.user.email %>
</p>

<%= link_to 'Edit', edit_patient_profile_path(@patient_profile), class: 'btn btn-warning' %> 

</div>
</div>
</div>
</div>